# Chapter 16: Pretraining an Encoder: The BERT 2 Language Model
Fine-tuning BERT with the HuggingFace API

Programs from the book: [_Python for Natural Language Processing_](https://link.springer.com/book/9783031575488)

__Author__: Pierre Nugues

In [1]:
import os
import torch
import numpy as np

## Dataset

In [2]:
from datasets import load_dataset

In [3]:
imdb = load_dataset('stanfordnlp/imdb')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
imdb

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

We can extract a small dataset for testing the whole pipeline

In [5]:
SMALL = True

In [6]:
if SMALL:
    imdb['train'] = imdb['train'].select(range(0, 25000, 100))
    imdb['test'] = imdb['test'].select(range(0, 25000, 100))

The dataset structure

In [7]:
imdb

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 250
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 250
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [8]:
train_set = imdb['train']

In [9]:
len(train_set)

250

In [10]:
train_set[0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.',
 'label': 0}

In [11]:
if not SMALL:
    print(train_set[12500])

In [12]:
test_set = imdb['test']

## Tokenizer

We create the tokenizer. These statements will download the model the first time we execute them. Again, it will be stored in a cache: `./~cache`

Alternatively, we can download it explicitely with the command:
```
git clone https://huggingface.co/distilbert-base-uncased
```

In [13]:
from transformers import AutoTokenizer

In [14]:
# model_name = "bert-base-uncased"
model_name = "distilbert-base-uncased"  # Downloaded automatically
# model_name = "~/.cache/distilbert-base-uncased" # Downloaded manually
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [15]:
train_set['text'][0]

'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.'

In [16]:
tokens = tokenizer(train_set['text'][0])

In [17]:
tokens.keys()

KeysView({'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 3836, 1010, 19846, 1010, 1998, 2496, 2273, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2054, 8563, 2033, 2055, 1045, 2572, 8025, 1011, 3756, 2003, 2008, 2871, 2086, 3283, 1010, 2023, 2001, 2641, 26932, 1012, 2428, 1010, 1996, 3348, 1998, 16371, 25469, 5019, 2024, 2261, 1998, 2521, 2090, 1010, 2130, 2059, 2009, 1005, 1055, 2025, 2915, 2066, 2070, 10036, 2135, 2081, 22555, 2080, 1012, 2096, 2026, 2406, 3549, 2568, 2424, 2009, 16880, 1010, 1999, 4507, 3348, 1998, 16371, 25469, 2024, 1037, 2350, 18785, 1999, 4467, 5988, 1012, 2130, 13749, 7849, 24544, 1010, 15835, 2037, 3437, 2000, 2204, 2214, 2879, 2198, 4811, 1010, 2018, 3348, 5019, 1999, 2010, 3152, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1045, 2079, 4012, 3549, 2094, 1996, 16587, 2005, 1996, 2755, 2008, 2151, 3348, 3491, 1999, 1996, 2143, 2003, 3491, 2005, 6018, 5682, 2738, 2084, 2074, 2000, 5213, 2111, 1998, 2191, 2769, 2000, 2022, 3491, 1999, 26932, 12370, 1999, 2637, 1012, 1045, 2572, 8025, 1011, 3756, 2003, 1037, 2204, 2143, 2005, 3087, 5782, 2000, 2817, 1996, 6240, 1998, 14629, 1006, 2053, 26136, 3832, 1007, 1997, 4467, 5988, 1012, 2021, 2428, 1010, 2023, 2143, 2987, 1005, 1056, 2031, 2172, 1997, 1037, 5436, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

In [18]:
tokens

{'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 3836, 1010, 19846, 1010, 1998, 2496, 2273, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2054, 8563, 2033, 2055, 1045, 2572, 8025, 1011, 3756, 2003, 2008, 2871, 2086, 3283, 1010, 2023, 2001, 2641, 26932, 1012, 2428, 1010, 1996, 3348, 1998, 16371, 25469, 5019, 2024, 2261, 1998, 2521, 2090, 1010, 2130, 2059, 2009, 1005, 1055, 2025, 2915, 2066, 2070, 10036, 2135, 2081, 22555, 2080, 1012, 2096, 2026, 2406, 3549, 2568, 2424, 2009, 16880, 1010, 1999, 4507, 3348, 1998, 16371, 25469, 2024, 1037, 2350, 18785, 1999, 4467, 5988, 1012, 2130, 13749, 7849, 24544, 1010, 15835, 2037, 3437, 2000, 2204, 2214, 2879, 2198, 4811, 1010, 2018, 3348, 5019, 1999, 2010, 3152, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1045, 2079, 4012, 3549, 2094, 1996, 16587, 2005, 1996, 2755, 2008, 2151, 3348, 3491, 1999, 1996, 2143, 2003, 3491, 2005, 6018, 5682, 2738, 2084, 2074, 2000, 5213, 2111, 1998, 2191, 2769, 2000, 2022, 3491, 1999, 26932, 12370, 1999, 2637, 1012, 1045, 2572, 8025, 1011, 3756, 2003, 1037, 2204, 2143, 2005, 3087, 5782, 2000, 2817, 1996, 6240, 1998, 14629, 1006, 2053, 26136, 3832, 1007, 1997, 4467, 5988, 1012, 2021, 2428, 1010, 2023, 2143, 2987, 1005, 1056, 2031, 2172, 1997, 1037, 5436, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [19]:
tokenizer.convert_ids_to_tokens(tokens['input_ids'])

['[CLS]',
 'i',
 'rented',
 'i',
 'am',
 'curious',
 '-',
 'yellow',
 'from',
 'my',
 'video',
 'store',
 'because',
 'of',
 'all',
 'the',
 'controversy',
 'that',
 'surrounded',
 'it',
 'when',
 'it',
 'was',
 'first',
 'released',
 'in',
 '1967',
 '.',
 'i',
 'also',
 'heard',
 'that',
 'at',
 'first',
 'it',
 'was',
 'seized',
 'by',
 'u',
 '.',
 's',
 '.',
 'customs',
 'if',
 'it',
 'ever',
 'tried',
 'to',
 'enter',
 'this',
 'country',
 ',',
 'therefore',
 'being',
 'a',
 'fan',
 'of',
 'films',
 'considered',
 '"',
 'controversial',
 '"',
 'i',
 'really',
 'had',
 'to',
 'see',
 'this',
 'for',
 'myself',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'the',
 'plot',
 'is',
 'centered',
 'around',
 'a',
 'young',
 'swedish',
 'drama',
 'student',
 'named',
 'lena',
 'who',
 'wants',
 'to',
 'learn',
 'everything',
 'she',
 'can',
 'about',
 'life',
 '.',
 'in',
 'particular',
 'she',
 'wants',
 'to',
 'focus',
 'her',
 'attention',
 '##s',
 'to',
 'making',
 'some',
 'sort',
 'of',
 'documentary',
 'on',
 'what',
 'the',
 'average',
 'sw',
 '##ede',
 'thought',
 'about',
 'certain',
 'political',
 'issues',
 'such',
 'as',
 'the',
 'vietnam',
 'war',
 'and',
 'race',
 'issues',
 'in',
 'the',
 'united',
 'states',
 '.',
 'in',
 'between',
 'asking',
 'politicians',
 'and',
 'ordinary',
 'den',
 '##ize',
 '##ns',
 'of',
 'stockholm',
 'about',
 'their',
 'opinions',
 'on',
 'politics',
 ',',
 'she',
 'has',
 'sex',
 'with',
 'her',
 'drama',
 'teacher',
 ',',
 'classmates',
 ',',
 'and',
 'married',
 'men',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'what',
 'kills',
 'me',
 'about',
 'i',
 'am',
 'curious',
 '-',
 'yellow',
 'is',
 'that',
 '40',
 'years',
 'ago',
 ',',
 'this',
 'was',
 'considered',
 'pornographic',
 '.',
 'really',
 ',',
 'the',
 'sex',
 'and',
 'nu',
 '##dity',
 'scenes',
 'are',
 'few',
 'and',
 'far',
 'between',
 ',',
 'even',
 'then',
 'it',
 "'",
 's',
 'not',
 'shot',
 'like',
 'some',
 'cheap',
 '##ly',
 'made',
 'porn',
 '##o',
 '.',
 'while',
 'my',
 'country',
 '##men',
 'mind',
 'find',
 'it',
 'shocking',
 ',',
 'in',
 'reality',
 'sex',
 'and',
 'nu',
 '##dity',
 'are',
 'a',
 'major',
 'staple',
 'in',
 'swedish',
 'cinema',
 '.',
 'even',
 'ing',
 '##mar',
 'bergman',
 ',',
 'arguably',
 'their',
 'answer',
 'to',
 'good',
 'old',
 'boy',
 'john',
 'ford',
 ',',
 'had',
 'sex',
 'scenes',
 'in',
 'his',
 'films',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'i',
 'do',
 'com',
 '##men',
 '##d',
 'the',
 'filmmakers',
 'for',
 'the',
 'fact',
 'that',
 'any',
 'sex',
 'shown',
 'in',
 'the',
 'film',
 'is',
 'shown',
 'for',
 'artistic',
 'purposes',
 'rather',
 'than',
 'just',
 'to',
 'shock',
 'people',
 'and',
 'make',
 'money',
 'to',
 'be',
 'shown',
 'in',
 'pornographic',
 'theaters',
 'in',
 'america',
 '.',
 'i',
 'am',
 'curious',
 '-',
 'yellow',
 'is',
 'a',
 'good',
 'film',
 'for',
 'anyone',
 'wanting',
 'to',
 'study',
 'the',
 'meat',
 'and',
 'potatoes',
 '(',
 'no',
 'pun',
 'intended',
 ')',
 'of',
 'swedish',
 'cinema',
 '.',
 'but',
 'really',
 ',',
 'this',
 'film',
 'doesn',
 "'",
 't',
 'have',
 'much',
 'of',
 'a',
 'plot',
 '.',
 '[SEP]']

In [20]:
tokenizer.model_max_length

512

In [21]:
tokenizer(train_set['text'][:3])

{'input_ids': [[101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 3836, 1010, 19846, 1010, 1998, 2496, 2273, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2054, 8563, 2033, 2055, 1045, 2572, 8025, 1011, 3756, 2003, 2008, 2871, 2086, 3283, 1010, 2023, 2001, 2641, 26932, 1012, 2428, 1010, 1996, 3348, 1998, 16371, 25469, 5019, 2024, 2261, 1998, 2521, 2090, 1010, 2130, 2059, 2009, 1005, 1055, 2025, 2915, 2066, 2070, 10036, 2135, 2081, 22555, 2080, 1012, 2096, 2026, 2406, 3549, 2568, 2424, 2009, 16880, 1010, 1999, 4507, 3348, 1998, 16371, 25469, 2024, 1037, 2350, 18785, 1999, 4467, 5988, 1012, 2130, 13749, 7849, 24544, 1010, 15835, 2037, 3437, 2000, 2204, 2214, 2879, 2198, 4811, 1010, 2018, 3348, 5019, 1999, 2010, 3152, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1045, 2079, 4012, 3549, 2094, 1996, 16587, 2005, 1996, 2755, 2008, 2151, 3348, 3491, 1999, 1996, 2143, 2003, 3491, 2005, 6018, 5682, 2738, 2084, 2074, 2000, 5213, 2111, 1998, 2191, 2769, 2000, 2022, 3491, 1999, 26932, 12370, 1999, 2637, 1012, 1045, 2572, 8025, 1011, 3756, 2003, 1037, 2204, 2143, 2005, 3087, 5782, 2000, 2817, 1996, 6240, 1998, 14629, 1006, 2053, 26136, 3832, 1007, 1997, 4467, 5988, 1012, 2021, 2428, 1010, 2023, 2143, 2987, 1005, 1056, 2031, 2172, 1997, 1037, 5436, 1012, 102], [101, 6659, 3185, 1012, 16371, 4246, 2056, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2122, 3210, 2024, 2074, 6039, 2121, 1012, 1996, 3185, 2001, 2919, 1012, 2339, 1045, 2031, 2000, 7818, 2006, 2008, 1045, 2123, 1005, 1056, 2113, 1012, 2023, 2003, 2525, 1037, 5949, 1997, 2026, 2051, 1012, 1045, 2074, 2359, 2000, 11582, 2500, 1012, 4468, 2023, 3185, 1012, 1996, 3772, 19237, 1998, 1996, 3015, 2003, 2074, 22822, 12356, 1012, 2919, 1999, 2296, 2126, 1012, 1996, 2069, 3835, 2518, 2055, 1996, 3185, 2024, 7939, 10993, 17712, 20718, 1005, 1055, 12682, 1012, 2130, 2008, 2001, 9868, 2295, 2011, 1037, 6659, 1998, 4895, 24045, 5732, 9040, 3496, 1012, 1996, 3185, 2003, 1037, 9996, 9530, 18886, 7178, 1998, 6135, 23653, 3538, 1997, 13044, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 7929, 2085, 1045, 2572, 2074, 2183, 2000, 17768, 2006, 10047, 18939, 2005, 2023, 5236, 3627, 1997, 2184, 3210, 1997, 3793, 6263, 1012, 2034, 1045, 5949, 2026, 2051, 3666, 2023, 2125, 2389, 1012, 2059, 3110, 15055, 2000, 11582, 2500, 1045, 3443, 2019, 4070, 2007, 10047, 18939, 2069, 2000, 7523, 2008, 1045, 2031, 2000, 4339, 1037, 10424, 8004, 6914, 9491, 2006, 1996, 2143, 2074, 2000, 4671, 2129, 2919, 1045, 2228, 2009, 2003, 1012, 6135, 14203, 1012, 102], [101, 2023, 2003, 2019, 2895, 2530, 1012, 2508, 26261, 8445, 5260, 2019, 2035, 2732, 3459, 1999, 1996, 12916, 4514, 1010, 2029, 2003, 6361, 1999, 2307, 11867, 7770, 7983, 1012, 1996, 17363, 1998, 12703, 2024, 2307, 1012, 2045, 2003, 2895, 1998, 6172, 1012, 5954, 3248, 1037, 7272, 7125, 2386, 2040, 3216, 21358, 7140, 2140, 1997, 1037, 15274, 2231, 1999, 1996, 2214, 2025, 2232, 19650, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 2364, 4009, 5963, 2003, 1996, 12991, 27086, 22330, 8713, 2008, 5365, 2038, 2467, 2081, 2046, 1037, 5394, 1012, 2130, 2043, 2023, 3185, 2001, 2081, 1010, 1996, 22330, 8713, 2001, 1996, 12991, 27086, 5394, 1010, 1998, 1996, 2028, 5954, 17509, 2428, 2038, 2261, 7494, 4519, 2015, 1012, 2002, 2003, 2785, 2000, 2010, 2048, 5826, 1010, 1998, 2008, 2515, 2507, 2032, 2019, 4469, 9812, 1997, 21553, 1998, 5622, 2912, 8553, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2174, 1010, 2002, 2003, 2061, 10369, 17701, 2232, 2000, 3071, 2842, 1010, 2009, 2003, 2524, 2000, 2428, 2729, 2005, 2032, 1010, 2030, 2000, 5138, 2032, 1012, 2002, 2003, 2172, 2066, 1996, 2028, 8789, 26666, 2530, 3494, 1006, 3013, 2025, 2008, 2919, 1007, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2145, 1010, 1996, 3576, 3494, 2024, 3243, 22249, 1012, 4787, 13962, 1010, 2548, 4907, 2080, 1010, 4302, 5253, 1010, 1998, 2500, 2191, 2023, 4276, 3666, 1012, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [22]:
classics = [
    'Tell me, O Muse, of that hero',
    'Many cities did he visit',
    'Exiled from home am I ;']

In [23]:
tokenizer(classics, truncation=True, padding=True, max_length=512)

{'input_ids': [[101, 2425, 2033, 1010, 1051, 18437, 1010, 1997, 2008, 5394, 102], [101, 2116, 3655, 2106, 2002, 3942, 102, 0, 0, 0, 0], [101, 14146, 2013, 2188, 2572, 1045, 1025, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

We tokenize the whole dataset with `map`

In [24]:
imdb_tokenized = imdb.map(lambda x: tokenizer(x['text'],
                                              truncation=True,
                                              padding=True,
                                              max_length=128),
                          batched=True)

In [25]:
imdb_tokenized['train'][:2]

{'text': ['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.',
  "Terrible movie. Nuff Said.<br /><br />These Lines are Just Filler. The movie was bad. Why I have to expand on that I don't know. This is already a waste of my time. I just wanted to warn others. Avoid this movie. The acting sucks and the writing is just moronic. Bad in every way. The only nice thing about the movie are Deniz Akkaya's breasts. Even that was ruined though by a terrible and unneeded rape scene. The movie is a poorly contrived and totally unbelievable piece of garbage.<br /><br />OK now I am just going to rag on IMDb for this stupid rule of 10 lines of text minimum. First I waste my time watching this offal. Then feeling compelled to warn others I create an account with IMDb only to discover that I have to write a friggen essay on the film just to express how bad I think it is. Totally unnecessary."],
 'label': [0, 0],
 'input_ids': [[101,
   1045,
   12524,
   1045,
   2572,
   8025,
   1011,
   3756,
   2013,
   2026,
   2678,
   3573,
   2138,
   1997,
   2035,
   1996,
   6704,
   2008,
   5129,
   2009,
   2043,
   2009,
   2001,
   2034,
   2207,
   1999,
   3476,
   1012,
   1045,
   2036,
   2657,
   2008,
   2012,
   2034,
   2009,
   2001,
   8243,
   2011,
   1057,
   1012,
   1055,
   1012,
   8205,
   2065,
   2009,
   2412,
   2699,
   2000,
   4607,
   2023,
   2406,
   1010,
   3568,
   2108,
   1037,
   5470,
   1997,
   3152,
   2641,
   1000,
   6801,
   1000,
   1045,
   2428,
   2018,
   2000,
   2156,
   2023,
   2005,
   2870,
   1012,
   1026,
   7987,
   1013,
   1028,
   1026,
   7987,
   1013,
   1028,
   1996,
   5436,
   2003,
   8857,
   2105,
   1037,
   2402,
   4467,
   3689,
   3076,
   2315,
   14229,
   2040,
   4122,
   2000,
   4553,
   2673,
   2016,
   2064,
   2055,
   2166,
   1012,
   1999,
   3327,
   2016,
   4122,
   2000,
   3579,
   2014,
   3086,
   2015,
   2000,
   2437,
   2070,
   4066,
   1997,
   4516,
   2006,
   2054,
   1996,
   2779,
   25430,
   14728,
   2245,
   2055,
   3056,
   2576,
   3314,
   102],
  [101,
   6659,
   3185,
   1012,
   16371,
   4246,
   2056,
   1012,
   1026,
   7987,
   1013,
   1028,
   1026,
   7987,
   1013,
   1028,
   2122,
   3210,
   2024,
   2074,
   6039,
   2121,
   1012,
   1996,
   3185,
   2001,
   2919,
   1012,
   2339,
   1045,
   2031,
   2000,
   7818,
   2006,
   2008,
   1045,
   2123,
   1005,
   1056,
   2113,
   1012,
   2023,
   2003,
   2525,
   1037,
   5949,
   1997,
   2026,
   2051,
   1012,
   1045,
   2074,
   2359,
   2000,
   11582,
   2500,
   1012,
   4468,
   2023,
   3185,
   1012,
   1996,
   3772,
   19237,
   1998,
   1996,
   3015,
   2003,
   2074,
   22822,
   12356,
   1012,
   2919,
   1999,
   2296,
   2126,
   1012,
   1996,
   2069,
   3835,
   2518,
   2055,
   1996,
   3185,
   2024,
   7939,
   10993,
   17712,
   20718,
   1005,
   1055,
   12682,
   1012,
   2130,
   2008,
   2001,
   9868,
   2295,
   2011,
   1037,
   6659,
   1998,
   4895,
   24045,
   5732,
   9040,
   3496,
   1012,
   1996,
   3185,
   2003,
   1037,
   9996,
   9530,
   18886,
   7178,
   1998,
   6135,
   23653,
   3538,
   1997,
   13044,
   1012,
   1026,
   7987,
   1013,
   1028,
   102]],
 'token_type_ids': [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0]],
 'attention_mask': [[1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1],
  [1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1]]}

## Fine-tuning

In [26]:
model_name

'distilbert-base-uncased'

In [27]:
from transformers import AutoModelForSequenceClassification

num_labels = 2
model = (AutoModelForSequenceClassification
         .from_pretrained(model_name, num_labels=num_labels))

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [28]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [29]:
from transformers import TrainingArguments

model_output_name = 'finetuned_imdb'
training_args = TrainingArguments(output_dir=model_output_name,
                                  num_train_epochs=2,
                                  learning_rate=2e-5,
                                  per_device_train_batch_size=32,
                                  per_device_eval_batch_size=32,
                                  weight_decay=0.01,
                                  eval_strategy='epoch',
                                  logging_strategy='no',  # we do not save ckeckpoints
                                  disable_tqdm=False)

In [30]:
def compute_accuracy(eval_output):
    labels_ids = eval_output.label_ids
    predictions = eval_output.predictions.argmax(axis=-1)
    return {'accuracy': np.mean(predictions == labels_ids)}

In [31]:
from transformers import Trainer

trainer = Trainer(model=model, args=training_args,
                  compute_metrics=compute_accuracy,
                  train_dataset=imdb_tokenized['train'],
                  eval_dataset=imdb_tokenized['test'],
                  processing_class=tokenizer)

In [32]:
trainer.train()

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=16, training_loss=0.6860556602478027, metrics={'train_runtime': 10.8593, 'train_samples_per_second': 46.043, 'train_steps_per_second': 1.473, 'total_flos': 16558424832000.0, 'train_loss': 0.6860556602478027, 'epoch': 2.0})

In [33]:
trainer.save_model()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
metrics = trainer.evaluate()
metrics

{'eval_loss': 0.6838580965995789, 'eval_accuracy': 0.608}

## Prediction with the model

We load the fine-tuned model

In [35]:
finetuned_model = AutoModelForSequenceClassification.from_pretrained(
    'finetuned_imdb')

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [36]:
input_ids = torch.LongTensor(imdb_tokenized['test']['input_ids'][-10:])
attention_mask = torch.LongTensor(
    imdb_tokenized['test']['attention_mask'][-10:])
labels = torch.LongTensor(imdb_tokenized['test']['label'][-10:])

In [37]:
input_ids

tensor([[  101,  1996,  3185,  ...,  1012,  2023,   102],
        [  101,  2108,  1037,  ...,  5632,  2296,   102],
        [  101,  2096,  2002,  ...,     0,     0,     0],
        ...,
        [  101,  4050,  1010,  ...,  2066,  2023,   102],
        [  101,  2023,  2143,  ...,  2522, 14515,   102],
        [  101,  4898,  1998,  ..., 12063,  1010,   102]])

In [38]:
labels

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
finetuned_model(input_ids, attention_mask=attention_mask, labels=labels)

SequenceClassifierOutput(loss=tensor(0.6863, grad_fn=<NllLossBackward0>), logits=tensor([[0.0021, 0.0519],
        [0.0399, 0.0457],
        [0.0232, 0.1028],
        [0.0347, 0.0059],
        [0.0357, 0.0270],
        [0.0522, 0.0416],
        [0.0598, 0.0611],
        [0.0428, 0.0607],
        [0.0112, 0.0515],
        [0.0402, 0.0339]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [40]:
finetuned_model(input_ids, attention_mask=attention_mask,
                labels=labels)[1].argmax(dim=-1)

tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

In [41]:
torch.softmax(finetuned_model(
    input_ids, attention_mask=attention_mask, labels=labels)[1], dim=-1)

tensor([[0.4875, 0.5125],
        [0.4986, 0.5014],
        [0.4801, 0.5199],
        [0.5072, 0.4928],
        [0.5022, 0.4978],
        [0.5027, 0.4973],
        [0.4997, 0.5003],
        [0.4955, 0.5045],
        [0.4899, 0.5101],
        [0.5016, 0.4984]], grad_fn=<SoftmaxBackward0>)

## Prediction with a Pipeline

This includes the tokenizer

In [42]:
from transformers import pipeline

ftuned_model_name = 'finetuned_imdb'
classifier = pipeline('text-classification',
                      model=ftuned_model_name)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [43]:
classifier(['I loved it!!!', 'I hate this movie!'])

[{'label': 'LABEL_0', 'score': 0.5524218678474426},
 {'label': 'LABEL_0', 'score': 0.5640742778778076}]

## Freezing Layers

In [44]:
model_name

'distilbert-base-uncased'

In [45]:
cnt = 0
for p in model.pre_classifier.parameters():
    print(p)
    cnt += 1
    if cnt > 10:
        break

Parameter containing:
tensor([[-0.0052, -0.0163, -0.0124,  ..., -0.0260,  0.0017, -0.0071],
        [-0.0089,  0.0226, -0.0035,  ...,  0.0196,  0.0027,  0.0035],
        [-0.0341,  0.0049,  0.0009,  ...,  0.0116,  0.0227, -0.0069],
        ...,
        [-0.0213,  0.0046, -0.0195,  ..., -0.0223, -0.0209, -0.0104],
        [-0.0177, -0.0134,  0.0429,  ..., -0.0073, -0.0165,  0.0007],
        [ 0.0398, -0.0090,  0.0097,  ...,  0.0103, -0.0167,  0.0111]],
       device='mps:0', requires_grad=True)
Parameter containing:
tensor([-7.1346e-05,  7.0475e-05, -9.3509e-06,  0.0000e+00, -7.9380e-06,
         1.8899e-06, -8.5134e-05, -5.7152e-05, -6.5961e-05,  8.8612e-05,
         9.2645e-05,  9.2906e-05, -1.1296e-04,  0.0000e+00, -1.0469e-05,
        -1.1016e-04, -5.6552e-06,  0.0000e+00, -4.9175e-05,  0.0000e+00,
         9.2608e-05,  1.2765e-05,  9.3864e-05,  1.0356e-04, -4.7946e-05,
         8.1432e-05, -5.6395e-05,  3.5268e-05, -5.3406e-05, -2.3781e-05,
         9.2649e-05, -9.5374e-05, -8.0994e-05, -5.9234e-05,  0.0000e+00,
        -6.9938e-05, -4.4963e-05, -8.1855e-05, -4.9430e-05,  0.0000e+00,
        -8.8665e-05,  8.6628e-05, -8.7342e-05,  4.4300e-05, -7.4227e-05,
        -3.9335e-05, -5.5154e-06,  9.0712e-05,  0.0000e+00,  3.5309e-05,
        -9.4997e-05,  8.5327e-05,  8.7185e-05,  7.2164e-05, -4.5762e-05,
         1.4422e-05,  5.4806e-05,  7.9391e-05, -5.8798e-05, -6.3508e-05,
         5.2072e-05,  1.5646e-06, -3.7502e-05, -5.3461e-05, -7.9653e-05,
        -7.9371e-05,  9.8592e-05, -7.1908e-05, -8.0834e-06,  1.8725e-05,
         1.0322e-04, -1.1812e-04,  7.5021e-05,  5.7450e-05,  2.9164e-05,
         5.8807e-06,  8.2529e-05, -6.9332e-05, -3.3306e-05, -3.4850e-06,
         1.7581e-05, -3.0087e-05,  6.2988e-05,  8.7938e-05, -8.9471e-05,
        -6.5393e-05, -1.0594e-04, -7.2938e-05, -3.8989e-05, -4.1812e-05,
        -8.4525e-06, -2.3942e-05, -7.0869e-05,  8.1381e-05, -1.3368e-04,
         1.7103e-05,  6.3343e-07, -1.0496e-04, -1.2903e-05, -2.3703e-05,
        -7.9372e-06, -6.1903e-05,  8.6903e-05,  0.0000e+00,  4.0936e-05,
         8.8045e-05,  8.7352e-05,  0.0000e+00,  6.3337e-05, -8.2198e-05,
         2.2459e-05, -9.5132e-05, -3.7476e-05,  1.3090e-04,  6.8539e-05,
         3.0757e-05,  0.0000e+00, -5.4026e-06, -7.9448e-05, -6.9716e-05,
        -6.4854e-05,  8.9436e-05, -8.3893e-05,  0.0000e+00,  0.0000e+00,
        -8.7205e-05,  1.8371e-06, -1.1975e-04,  9.6739e-06, -6.7906e-06,
        -8.4852e-05, -7.0877e-05,  7.4294e-05, -6.0881e-05,  6.3068e-05,
         5.5296e-05, -5.5265e-05, -1.4541e-05,  6.1722e-05,  1.4762e-05,
        -5.3382e-05, -8.2462e-05, -8.8386e-05,  1.1651e-04,  4.8834e-05,
        -1.1346e-04,  3.8912e-05,  8.9435e-05, -6.4674e-05,  6.2967e-05,
        -9.7713e-05,  8.3211e-05, -6.7766e-05,  4.6889e-06,  6.3505e-05,
        -9.0584e-05,  4.7069e-06, -6.7153e-05, -8.3928e-05, -3.5149e-05,
        -2.5752e-05,  0.0000e+00,  6.2644e-05, -3.9349e-05,  5.5072e-05,
         0.0000e+00,  2.7185e-05,  3.5041e-05, -2.1555e-05,  8.5531e-05,
        -7.7051e-05,  7.6827e-05,  6.7292e-05,  0.0000e+00, -1.0883e-04,
        -9.8941e-05,  1.7886e-05,  1.5409e-05,  1.4595e-04, -2.1874e-05,
        -2.6398e-05,  3.9046e-05, -9.5824e-05,  0.0000e+00,  5.3897e-05,
        -7.9291e-05,  9.7775e-05,  6.7686e-05,  8.6663e-05,  7.9334e-05,
        -9.5202e-05, -1.9380e-05, -1.0825e-04,  1.0952e-04, -9.8301e-06,
         1.0307e-04, -1.7360e-05, -9.9886e-06,  0.0000e+00,  1.0850e-04,
         1.0245e-04, -5.3336e-05,  4.7837e-05,  3.7720e-05, -8.2099e-05,
        -9.1859e-05, -2.9413e-05, -7.3734e-05,  9.4490e-05, -6.6118e-05,
         6.4605e-05,  7.4651e-05,  0.0000e+00,  0.0000e+00,  3.9569e-05,
        -5.4975e-05,  0.0000e+00, -1.7002e-05,  8.3748e-05, -2.8103e-05,
        -6.5731e-05,  7.5818e-07, -8.0176e-05,  0.0000e+00, -8.9562e-05,
         1.3571e-05,  7.7153e-05, -8.2686e-05,  1.1051e-04, -9.0172e-05,
         8.2135e-05,  8.2231e-05,  7.6304e-05, -1.1333e-04,  0.0000e+00,
        -2.6535e-05, -1.1843e-05,  8.4943e-05,  1.0924e-04, -7.9930e-05,
         0.0000e+00,  0.0000e+00, -1.0870e-04,  7.5945e-05,  3.3564e-07,
         2.4379e-06,  7.5766e-05,  7.6122e-05, -8.5528e-05,  5.5935e-05,
        -5.3134e-05, -1.1158e-05, -6.9877e-05, -1.6561e-05,  7.4654e-05,
        -9.2650e-05, -9.1346e-05, -8.7501e-05, -8.4212e-05, -6.8384e-05,
         9.1389e-05, -5.9911e-06, -2.5166e-06,  6.5260e-05,  2.7593e-05,
        -6.8012e-05,  6.0802e-05,  9.6417e-06,  9.1525e-05,  5.8330e-06,
        -5.0503e-08,  2.5483e-05,  7.9375e-06,  9.2370e-05,  0.0000e+00,
         2.1836e-05,  1.3808e-05, -9.6442e-06,  2.3652e-06,  1.4821e-05,
         0.0000e+00, -1.0709e-04,  0.0000e+00, -4.3957e-05,  2.2656e-05,
        -8.4429e-05, -1.7043e-05, -6.8649e-05,  3.4720e-05, -8.2572e-05,
        -3.9852e-05,  6.5709e-05, -4.0116e-05, -1.1179e-04, -9.6805e-05,
        -4.5218e-05, -8.8064e-05, -1.0389e-04, -3.6980e-05,  9.1472e-05,
         0.0000e+00,  0.0000e+00,  1.3570e-04,  0.0000e+00,  5.7449e-05,
         9.1733e-05, -2.7515e-05,  8.0220e-05, -1.4883e-05, -1.8639e-05,
         4.9754e-06, -2.4822e-05,  6.1814e-05, -1.0068e-04, -1.0105e-04,
         6.4629e-05, -7.5380e-05,  3.4903e-05, -6.3649e-05,  0.0000e+00,
         7.5997e-05, -7.1150e-05,  8.8302e-05,  9.1377e-06, -1.1577e-04,
         8.7892e-05,  3.0004e-05,  0.0000e+00, -9.7991e-05, -9.6160e-05,
         2.8417e-06, -9.8643e-06, -7.3415e-05, -1.3559e-04, -2.1140e-05,
        -8.7909e-05, -9.0032e-05,  6.0466e-05, -2.9482e-05,  1.0689e-04,
        -3.8073e-05, -7.0203e-05,  3.6915e-05, -1.0053e-04, -1.0768e-04,
        -1.1746e-04, -6.9834e-05,  9.0673e-05,  9.2963e-05, -9.1332e-05,
        -9.0166e-05,  1.8848e-05, -2.6443e-05,  0.0000e+00, -9.2140e-05,
        -2.3215e-05,  3.2727e-05,  6.6650e-05,  4.0773e-05, -4.5214e-06,
        -6.4688e-05,  8.2272e-05,  7.2082e-05,  7.8941e-05, -9.5720e-05,
         8.4896e-05, -5.6434e-05, -6.9909e-05,  0.0000e+00, -1.3826e-05,
         2.4028e-05, -8.6347e-06, -3.6134e-05, -8.8049e-05, -1.2266e-04,
         7.7092e-05,  2.1272e-05, -1.1190e-04,  7.6417e-05, -1.3760e-05,
        -2.7695e-05,  9.9856e-05,  0.0000e+00,  8.1029e-05, -5.4543e-05,
         0.0000e+00,  0.0000e+00, -8.3561e-07, -8.8661e-05,  3.2281e-05,
        -6.8319e-05,  9.1656e-05, -4.0401e-05, -6.0767e-05,  8.0111e-05,
        -9.7339e-05,  1.4939e-05, -3.0683e-06, -1.7345e-05,  4.8250e-05,
        -1.1128e-04, -5.3588e-05,  0.0000e+00, -6.9863e-05,  0.0000e+00,
        -5.7204e-05, -8.4066e-05, -8.2160e-05, -5.0472e-05,  0.0000e+00,
        -9.7172e-05,  0.0000e+00, -7.3024e-05,  8.9296e-05, -1.0004e-04,
        -8.2441e-05,  8.7540e-05, -9.4776e-05,  0.0000e+00,  2.3861e-05,
        -9.0778e-05, -3.6675e-05,  0.0000e+00, -7.6875e-05, -6.6298e-06,
         2.5271e-05,  1.0842e-04, -1.0511e-04,  1.2148e-05, -2.0776e-05,
         0.0000e+00,  0.0000e+00,  7.9625e-06, -8.5488e-06,  9.2309e-05,
         8.0677e-05,  6.8440e-05, -3.0500e-05,  7.6804e-05,  4.0019e-05,
         1.0363e-04, -7.3502e-05,  6.2582e-05,  9.2037e-05, -7.2639e-06,
         7.9379e-06, -1.0665e-04, -1.2288e-04, -1.3220e-04, -2.2869e-06,
        -4.9091e-05,  0.0000e+00, -6.8897e-05,  0.0000e+00,  8.8084e-05,
         1.7653e-06, -9.6939e-05,  6.0483e-05, -2.4888e-05, -7.7924e-05,
         9.9249e-07, -4.3363e-05, -6.7316e-06,  4.1237e-05, -6.5622e-06,
         0.0000e+00, -8.4250e-05,  6.2510e-05,  1.0843e-04, -4.2149e-05,
         5.3796e-05, -7.7877e-05, -6.7902e-06,  3.6389e-05,  0.0000e+00,
         8.0245e-05, -2.0894e-05,  0.0000e+00,  2.9897e-05,  9.6228e-05,
        -5.3249e-05, -9.1753e-05,  4.9045e-05,  9.0994e-05, -7.5258e-05,
        -1.2277e-05,  6.4608e-05,  1.7655e-06,  5.7300e-05,  2.5484e-05,
         5.6476e-05, -7.0431e-05,  0.0000e+00,  5.8078e-05, -1.0945e-04,
        -3.8486e-05, -1.3619e-04, -4.4125e-05,  4.5581e-05,  0.0000e+00,
        -8.7180e-05, -1.1583e-04, -6.5166e-06,  7.1227e-05,  0.0000e+00,
         4.3098e-05, -4.8627e-05,  9.2397e-05,  0.0000e+00,  3.9541e-05,
         5.5684e-05,  8.7193e-05,  1.1284e-05,  8.9218e-06, -1.0928e-04,
        -7.4962e-05,  9.2559e-05,  6.4970e-05,  5.7308e-05,  0.0000e+00,
        -5.0459e-05,  7.1727e-05, -8.0112e-05,  6.7861e-06,  3.8017e-06,
        -2.2187e-05, -7.7202e-05, -1.2928e-04, -8.2425e-05, -8.4051e-05,
         7.2193e-05,  0.0000e+00, -8.7919e-05,  4.4100e-06, -1.0936e-04,
         6.0503e-05,  1.7655e-06,  6.1441e-05,  2.6287e-05,  3.1223e-06,
        -3.9584e-05,  0.0000e+00,  5.5784e-05,  8.0828e-05,  7.2532e-05,
         7.0352e-05,  2.0951e-05,  9.1715e-05,  7.8501e-06, -7.4636e-05,
         0.0000e+00, -7.0737e-05, -3.0309e-05,  1.9949e-05,  7.7639e-05,
        -6.1448e-05, -6.3100e-05, -1.6510e-05, -2.3988e-05,  1.2710e-04,
         5.7932e-05, -5.4415e-05,  5.8747e-05,  7.2200e-05,  6.9485e-05,
         2.7511e-05,  1.0027e-04,  6.0542e-05, -9.4310e-05,  4.5107e-05,
         5.9909e-05,  0.0000e+00, -5.3074e-05,  6.8114e-05, -7.7310e-05,
         0.0000e+00, -3.9418e-05,  8.8587e-05, -7.1734e-05,  0.0000e+00,
        -7.4796e-06,  1.0187e-04, -5.4319e-05,  2.8454e-05,  5.7719e-06,
        -6.0257e-05, -7.2701e-05,  1.3225e-04,  6.2999e-05,  4.9775e-05,
        -3.0972e-05, -6.5901e-05, -2.1075e-05,  6.5832e-05, -1.2152e-06,
        -4.4866e-05,  6.3502e-05, -8.9320e-06,  8.6013e-05,  9.5812e-05,
         1.5295e-05,  7.1455e-05, -1.1886e-05,  8.6345e-05, -6.6112e-05,
        -7.5360e-05,  8.4317e-05, -1.0330e-04,  0.0000e+00, -8.0700e-05,
        -2.1273e-05,  5.1087e-06, -1.1278e-04,  4.2438e-05,  7.5756e-05,
         1.2677e-05, -1.1010e-04,  2.3391e-06,  1.8413e-05, -7.2640e-05,
         6.3818e-05, -2.4201e-05, -5.7382e-05,  0.0000e+00,  7.5815e-05,
         9.6411e-05, -3.6856e-05,  2.5065e-05,  6.9072e-05,  7.6991e-05,
         1.0544e-05, -2.9547e-05, -4.2867e-05, -2.6864e-05,  0.0000e+00,
         4.0651e-05, -7.1959e-05,  2.7513e-05, -6.3288e-05, -6.6329e-06,
         8.3938e-05,  8.6353e-05,  0.0000e+00, -7.9363e-05, -3.4570e-05,
         0.0000e+00, -7.0420e-05,  5.8331e-05,  8.7472e-05,  0.0000e+00,
        -6.0376e-05, -4.7153e-05,  3.5009e-05,  0.0000e+00,  8.3700e-05,
        -7.5537e-05,  5.6841e-05, -6.1154e-05,  2.4084e-05,  7.3715e-05,
        -9.0088e-05, -3.9697e-05,  8.4324e-05,  6.6010e-05,  4.0672e-05,
        -5.4253e-05, -1.0834e-04, -7.0870e-05,  1.1284e-04,  2.0108e-05,
         0.0000e+00, -2.0769e-05,  0.0000e+00,  1.4962e-05,  6.5140e-05,
         9.2423e-05, -1.0881e-04, -1.1120e-04,  0.0000e+00, -9.7841e-05,
         3.4653e-05,  1.1326e-05, -5.7261e-05, -8.0590e-05, -7.2599e-05,
        -6.8756e-06, -6.7143e-05, -6.2514e-05, -1.9789e-05, -4.6955e-05,
         9.3101e-05,  5.6525e-07,  0.0000e+00,  0.0000e+00, -6.7903e-05,
         9.6282e-05,  0.0000e+00,  0.0000e+00,  9.5334e-05,  9.3431e-05,
         3.9943e-07, -3.0703e-05,  8.8066e-05, -3.0728e-05, -3.6106e-05,
        -8.9008e-05,  9.5655e-05, -4.2506e-05,  4.7255e-05,  0.0000e+00,
        -4.3948e-05,  6.4024e-05,  4.0360e-05,  6.8897e-05,  5.8873e-05,
        -1.0057e-04,  1.2901e-04,  8.2569e-06,  8.5607e-05,  0.0000e+00,
        -2.0701e-05, -7.9378e-06,  3.6428e-06, -9.8402e-05, -8.8246e-05,
         7.4126e-05, -8.3885e-05, -9.2656e-05,  6.4752e-05,  7.5190e-05,
         7.6818e-05, -8.5420e-05, -6.0074e-05, -4.2673e-05, -2.7869e-05,
         4.0614e-05,  0.0000e+00, -6.0793e-05, -1.0728e-04,  5.5074e-05,
         7.9768e-05, -7.6496e-05, -6.2124e-05, -7.9368e-06, -2.4688e-05,
        -8.0141e-05,  6.3152e-05,  3.0531e-05, -3.5186e-05, -8.3650e-05,
         5.4999e-05, -4.7264e-06, -9.9275e-05, -7.3638e-05,  0.0000e+00,
        -6.5683e-06, -6.4500e-05,  2.9106e-05,  1.4899e-05,  9.7886e-05,
        -8.2212e-05,  6.1134e-05,  6.7620e-05, -1.2914e-05,  7.8072e-05,
        -9.5848e-05,  1.8198e-06, -8.1081e-05], device='mps:0',
       requires_grad=True)

In [46]:
def count_parameters(model):
    total = 0
    trainable = 0
    for params in model.parameters():
        total += params.numel()
        if params.requires_grad:
            trainable += params.numel()
    return {'total': total, 'trainable': trainable}

In [47]:
count_parameters(model)

{'total': 66955010, 'trainable': 66955010}

We reload the original model and we freeze some layers

In [48]:
from transformers import AutoModelForSequenceClassification

num_labels = 2
model_freezed = (AutoModelForSequenceClassification
                 .from_pretrained(model_name,
                                  num_labels=num_labels,
                                  attn_implementation='eager'))

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [49]:
model_freezed

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [50]:
count_parameters(model_freezed)

{'total': 66955010, 'trainable': 66955010}

In [51]:
count_parameters(model_freezed.pre_classifier)

{'total': 590592, 'trainable': 590592}

In [52]:
count_parameters(model_freezed.classifier)

{'total': 1538, 'trainable': 1538}

In [53]:
for param in model_freezed.parameters():
    param.requires_grad = False

In [54]:
for param in model_freezed.pre_classifier.parameters():
    param.requires_grad = True

for param in model_freezed.classifier.parameters():
    param.requires_grad = True

In [55]:
count_parameters(model_freezed)

{'total': 66955010, 'trainable': 592130}

This is to be compared with the original model

In [56]:
count_parameters(model)

{'total': 66955010, 'trainable': 66955010}

In [57]:
from transformers import Trainer

trainer = Trainer(model=model_freezed, args=training_args,
                  compute_metrics=compute_accuracy,
                  train_dataset=imdb_tokenized['train'],
                  eval_dataset=imdb_tokenized['test'],
                  processing_class=tokenizer)

In [58]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=16, training_loss=0.6943986415863037, metrics={'train_runtime': 4.3907, 'train_samples_per_second': 113.878, 'train_steps_per_second': 3.644, 'total_flos': 16558424832000.0, 'train_loss': 0.6943986415863037, 'epoch': 2.0})

In [59]:
metrics = trainer.evaluate()
metrics

{'eval_loss': 0.6932036280632019, 'eval_accuracy': 0.52}